[package]
name = "plog"
version = "0.2.3"
edition = "2021"
repository = "https://github.com/Defmc/plog"
description = "A pretty logger written for Rust programs "
license = "MIT"
keywords = ["log"]
categories = ["development-tools", "accessibility", "command-line-utilities", "config"]

[dependencies]
crossterm = { version = "0.23.1", optional = true }
parking_lot = { version = "0.12.0", optional = true }
chrono = { version = "0.4.19", optional = true }

[dev-dependencies]
bencher = "0.1.5"

[[bench]]
name = "comparision"
path = "src/bench.rs"
harness = false

[features]
date = ["chrono"]
time = ["chrono"]
context = []
impls = []
colored = ["crossterm"]
persistent = ["parking_lot"]
