[package]
name = "plog"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.23.1"
parking_lot = { version = "0.12.0", optional = true }
chrono = { version = "*", optional = true }

[features]
datetime = ["chrono"]
context = []
persistent = ["parking_lot"]
