[package]
name = "plog"
version = "0.1.1"
edition = "2021"
repository = "https://github.com/Defmc/plog"
description = "A pretty logger written for Rust programs "
license = "MIT"
keywords = ["log"]
categories = ["development-tools", "accessibility", "command-line-utilities", "config"]

[dependencies]
crossterm = "0.23.1"
parking_lot = { version = "0.12.0", optional = true }
chrono = { version = "0.4.19", optional = true }

[features]
datetime = ["chrono"]
context = []
persistent = ["parking_lot"]
