[package]
name = "plog"
version = "0.2.10"
edition = "2021"
repository = "https://github.com/Defmc/plog"
description = "A modular pretty logger written for Rust programs"
license = "MIT"
keywords = ["log", "testing", "text", "utility"]
categories = ["development-tools", "accessibility", "command-line-utilities", "config"]

[dependencies]
crossterm = { version = "0.23.1", optional = true }
parking_lot = { version = "0.12.0", optional = true }
chrono = { version = "0.4.19", optional = true }

[dev-dependencies]
tokio = { version = "1.17.0", features = ["rt", "macros", "rt-multi-thread", "time"] }

[features]
date = ["chrono"]
time = ["chrono"]
context = []
impls = []
colored = ["crossterm"]
persistent = ["parking_lot"]
